#!/bin/sh
export PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export HOME='/root'
export PS1='\w \h\$ '
HOSTNAME='minlin'
UDHCPC_ARGS=

mkdir -p /dev /proc /sys
mount -t devtmpfs devtmpfs /dev -o size=4k
mount -t proc     proc     /proc
mount -t sysfs    sysfs    /sys
mount -t debugfs  debugfs  /sys/kernel/debug

if [ x"$(command -v klogd)" != x ]; then
	$(command -v klogd)
fi
if [ x"$(command -v syslogd)" != x ]; then
	$(command -v syslogd) -C
	UDHCPC_ARGS='-S'
fi

echo '4 4 1 7' >/proc/sys/kernel/printk
cat <<EOF


Boot took $(cut -d' ' -f1 /proc/uptime) seconds

        _       _     __ _                  
  /\/\ (_)_ __ (_)   / /(_)_ __  _   ___  __
 /    \| | '_ \| |  / / | | '_ \| | | \ \/ /
/ /\/\ \ | | | | | / /__| | | | | |_| |>  < 
\/    \/_|_| |_|_| \____/_|_| |_|\__,_/_/\_\ 


Welcome to mini_linux


EOF

for arg in $(cat /proc/cmdline | tr '[:upper:]' '[:lower:]'); do
    if [ x"${arg}" = xip4 ]; then
        sysctl -w net.ipv6.conf.all.disable_ipv6=1
    fi
done

for arg in $(cat /proc/cmdline | tr '[:upper:]' '[:lower:]'); do
    if [ x"$(command -v udhcpc)" != x -a x"${arg}" = xnet ]; then
        echo '*** INIT NETWORK ***'
        for netif in $(ls /sys/class/net); do
            ifconfig ${netif} 0.0.0.0 up
        done
        $(command -v udhcpc) -R -x hostname:${HOSTNAME} ${UDHCPC_ARGS}
    fi
done

hostname ${HOSTNAME}
loadkmap </usr/share/keymaps/i386/qwertz/de-latin1.bmap
cd ${HOME}
setsid cttyhack sh
poweroff -f
